openapi: 3.0.1
info:
  title: Swagger CVD
  description: CVD api description
  version: 1.0.0
servers:
- url: http://{host}:{port}/api/v1
  variables:
    host:
      default: localhost
    port:
      default: "10081"
tags:
- name: file
  description: File operation
- name: vocabulary
  description: Vocabulary data operation
- name: example
  description: Example data operation
paths:
  /upload:
    post:
      tags:
      - file
      summary: Upload the file to the server
      description: |
        Uploads the file selected by the client to the server.
        When editing_vocabulary is uploaded, its check integrity.
        When editing_vocabulary is uploaded, please upload editing_vocabulary_meta together.
      operationId: upload_file
      requestBody:
        description: Select the file to upload.
        content:
          multipart/form-data:
            schema:
              $ref: '#/components/schemas/Upload'
      responses:
        "200":
          description: |
            Upload is completed. 
            If the client uploads the vocabulary data, call the load API.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: |
            File Format Error.
            ex. Invalid file uploaded.
            Set the error file name for the message.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                result: 0
                message: editing_vocabulary.csv
        "404":
          description: |
            Database Error.
            ex. Database is timeout.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckErrorResponse'
              example:
                result: 0
                message: Database connection timeout.
        "409":
          description: |
            Integrity check Error.
            phase : Returns the phase in which the error occurred.
            "1" means it was in the term check phase error.
            "2" means it was in the preferred_label check phase error.
            "3" means it was in the lang check phase error.
            "4" means it was in the uri check phase error.
            "5" means it was in the broader_term check phase error.
            "6" means it was in the other_voc_syn_uri check phase error.
            "7" means it was in the term_description check phase error.
            "8" means it was in the created_time check phase error.
            "9" means it was in the modified_time check phase error.
            "10" means it was in the synonym_candidate check phase error.
            "11" means it was in the broader_term_candidate check phase error.
            "12" means it was in the position_x check phase error.
            "13" means it was in the position_y check phase error.
            "14" means it was in the color1 check phase error.
            "15" means it was in the color2 check phase error.
            "16" means it was in the confirm check phase error.
            "90" means it was in the combination check phase error.
            "99" means it was in the other_unknown check phase error.
            terms : Returns terms in which the error occurred.
            langs : Returns language in which the error occurred.
            reason : Returns the check error reason code.
            file_type: Returns which file cause error. 0 editing volabulary, 1,2,3 reference vocabulary, 4 editing volabulary meta.
            
            phase 1, reason 0 (This returns only one error even if there are many)
            条件を満たさない用語列が空白のものが有ります。代表語のURIはｘｘｘです。行を削除するか、空白の条件を満たすように編集した後に再読み込みしてください。
            phase 1, reason 1 (This returns only one error even if there are many)
            用語名列で空白のものが存在条件を満たしていますが、複数行あります。代表語のURIはｘｘｘです。行を削除するか、用語を入力した後に再読み込みしてください。
            phase 1, reason 2 (This returns only one error even if there are many)
            用語名列で空白のものが存在条件を満たしていますが、同一言語の同義グループに値のある行があります。代表語のURIはｘｘｘです。行を削除するか、用語を入力した後に再読み込みしてください。
            phase 1, reason 5
            用語名列で用語a, b, c @langが重複しています。行を削除など、重複しないように編集した後に再読み込みしてください。
            phase 2, reason 0 (This returns only one error group even if there are many error group)
            同義関係と思われる、用語a,b,cの言語ごとの代表語を1つに揃えた後に再読み込みしてください。
            pahse 2, reason 1 (This returns only one error group even if there are many error group)
            同義関係の用語a,b,cの中に、どの言語にも代表語が無いです。いずれかの言語の代表語を設定した後に再読み込みしてください。
            pahse 2, reason 2 (This returns only one error group even if there are many error group)
            複数の同義関係の用語a,b,c, @langで同じ代表語を持っています。異なる同義語では異なる代表語を持つようにした後に再読み込みしてください。
            phase 3, reason 0
            「言語」列がja, enもしくは空白以外が含まれています。ja, en, 空文字を記入した後に再読み込みしてください。
            phase 4, reasn 0
            「代表語のURI」列に空白または異なる語彙体系のURIが含まれています。同じ語彙体系のURIを記入した後に再読み込みしてください。
            phase 5, reason 0
            「上位語のURI」列に空白または異なる語彙体系のURIが含まれています。同じ語彙体系のURIを記入した後に再読み込みしてください。
            phase 5, reason 1 (This returns only one error even if there are many)
            用語a, b, c で上位語のURIが一つに揃っていません。一つになるように編集した後に再読み込みしてください。
            phase 5, reason 2 (This returns only one error even if there are many)
            用語a, b, c で上位語のURIとして指定された用語が存在しません。URIを直すか削除するかして編集した後に再読み込みしてください。
            phase 5, reason 3 (This returns only one error even if there are many)
            用語a, b, c で、上下関係性が循環しています。上位語を修正した後に再読み込みしてください。
            phase 6, reason 0 (This returns only one error even if there are many)
            同義関係の用語a,b,c で、他語彙体系の同義語のURIが同義語内で異なります。1つに揃えた後に再読み込みしてください。
            phase 7, reason 0 (This returns only one error even if there are many)
            同義関係の用語a@ja,b@ja,c@jaで、用語の説明が異なっています。1つに揃えた後に再読み込みしてください。
            phase 8, reason 0 (This returns only one error even if there are many)
            同義関係の用語a@ja,b@ja,c@jaで、作成日が異なっています。1つに揃えた後に再読み込みしてください。
            phase 9, reason 0 (This returns only one error even if there are many)
            同義関係の用語a@ja,b@ja,c@jaで、最終更新日が異なっています。1つに揃えた後に再読み込みしてください。
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckErrorResponse'
              example:
                phase: 2
                terms:
                - a
                - b
                - c
                reason: 0
        "411":
          description: |
            File Format Error.
            ex. Invalid file uploaded.
            Set the error file name for the message.
            phase -1, reason 0: Something is wrong.
            phase 0, reason 0: Data Format Error.
            phase 1, reason 0: for editing vocaburaly, some of a required columns are not found. Missing colmuns are in terms parameter.
            phase 2, reason 0: for editing vocaburaly meta, some of a required columns are not found. Missing colmuns are in terms parameter.
            phase 3, reason 0: for reference vocaburaly1, some of a required columns are not found. Missing colmuns are in terms parameter.
            phase 4, reason 0: for reference vocaburaly2, some of a required columns are not found. Missing colmuns are in terms parameter.
            phase 5, reason 0: for reference vocaburaly3, some of a required columns are not found. Missing colmuns are in terms parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckErrorResponse'
              example:
                result: 0
                message: editing_vocabulary.csv
      x-swagger-router-controller: swagger_server.controllers.file_controller
      x-codegen-request-body-name: body
      x-openapi-router-controller: swagger_server.controllers.file_controller
  /download/{file_type}:
    get:
      tags:
      - file
      summary: Download the file from the server
      operationId: download_file
      parameters:
      - name: file_type
        in: path
        description: |
          Specify for editing_vocabulary or editing_vocabulary_meta or controlled_vocabulary.
          It downloads the selected file.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: out_format
        in: query
        description: |
          Specify the file format.
          When editing_vocabulary is set, the format is csv.
          when controlled_vocabulary is set, the format is n3, nquads, nt, trix, turtle, xml, json-ld.
        required: true
        style: form
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: |
            Download is complete.
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
                x-content-type: application/octet-stream
        "400":
          description: |
            Bad Request
            ex. Invalid parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: "Not Found  \nex. Download file not found.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-swagger-router-controller: swagger_server.controllers.file_controller
      x-openapi-router-controller: swagger_server.controllers.file_controller
  /vocabulary/{file_type}:
    get:
      tags:
      - vocabulary
      summary: Get vocabulary data by type
      operationId: get_vocabulary_data
      parameters:
      - name: file_type
        in: path
        description: |
          Specify for editing_vocabulary, reference_vocabulary1, etc.
          When editing_vocabulary is set, it gets editing vocabulary data.
          When reference_vocabulary1 is set, it gets reference vocabulary1 data.
          When reference_vocabulary2 is set, it gets reference vocabulary2 data.
          When reference_vocabulary3 is set, it gets reference vocabulary3 data.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: |
            Get vocabulary data is Success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetAllSuccessResponse'
        "400":
          description: |
            Bad Request
            ex. Invalid parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: "Not Found  \nex. Download file not found.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-swagger-router-controller: swagger_server.controllers.vocabulary_controller
      x-openapi-router-controller: swagger_server.controllers.vocabulary_controller
  /vocabulary/{file_type}/{term}:
    get:
      tags:
      - vocabulary
      summary: Get editing vocabulary term
      operationId: get_vocabulary_term
      parameters:
      - name: file_type
        in: path
        description: |
          Specify only editing_vocabulary.  It gets editing vocabulary data.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: term
        in: path
        description: |
          Specify the term to request.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        "200":
          description: |
            Return to vocabulary data.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EditingVocabulary'
        "400":
          description: |
            Bad Request
            ex. Invalid parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: "Not Found  \nex. Request term not found.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-swagger-router-controller: swagger_server.controllers.vocabulary_controller
      x-openapi-router-controller: swagger_server.controllers.vocabulary_controller
    post:
      tags:
      - vocabulary
      summary: Add or Update editing vocabulary terms
      operationId: post_vocabulary_term
      parameters:
      - name: file_type
        in: path
        description: |
          Specify only editing_vocabulary. It gets editing vocabulary data. 
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: term
        in: path
        description: Specify the update term
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/EditingVocabulary'
        required: true
      responses:
        "200":
          description: |
            Add or Update editing vocabulary data success.
            Return updated EditingVocabulary list.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/EditingVocabulary'
                x-content-type: application/json
        "400":
          description: |
            Bad Request
            ex. Invalid parameter.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        "404":
          description: "Not Found  \nex. Request term not found.\n"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-swagger-router-controller: swagger_server.controllers.vocabulary_controller
      x-openapi-router-controller: swagger_server.controllers.vocabulary_controller
      x-codegen-request-body-name: body
components:
  schemas:
    Upload:
      type: object
      properties:
        editing_vocabulary:
          type: string
          description: editing_vocabulary is a csv file
          format: binary
        editing_vocabulary_meta:
          type: string
          description: editing_vocabulary_meta is a csv file
          format: binary
        reference_vocabulary1:
          type: string
          description: reference_vocabulary1 is a csv file
          format: binary
        reference_vocabulary2:
          type: string
          description: reference_vocabulary2 is a csv file
          format: binary
        reference_vocabulary3:
          type: string
          description: reference_vocabulary3 is a csv file
          format: binary
    EditingVocabulary:
      type: object
      properties:
        id:
          type: integer
          format: int64
        term:
          type: string
        preferred_label:
          type: string
        language:
          type: string
        uri:
          type: string
        broader_term:
          type: string
        synonym:
          type: array
          items:
            type: string
        other_voc_syn_uri:
          type: string
        term_description:
          type: string
        created_time:
          type: string
        modified_time:
          type: string
        synonym_candidate:
          type: array
          items:
            type: string
        broader_term_candidate:
          type: array
          items:
            type: string
        postion_x:
          type: string
        postion_y:
          type: string
        color1:
          type: string
        color2:
          type: string
      example:
        id: 1
        term: os
        preferred_label: os
        language: ja
        uri: http://test/0/os
        broader_term: http://myVocab/3
        synonym: オペレーティングシステム
        other_voc_syn_uri: http://otherVocab/16
        term_description: 用語の説明です
        created_time: "2021-04-02T12:43:02Z"
        modified_time: "2021-04-08T16:07:59Z"
        synonym_candidate: 基本ソフト
        broader_term_candidate: プログラム
        postion_x: "100"
        postion_y: "100"
        color1: black
        color2: black
    EditingVocabularyMeta:
      type: object
      properties:
        id:
          type: integer
          format: int64
        meta_name:
          type: string
        meta_enname:
          type: string
        meta_version:
          type: string
        meta_prefix:
          type: string
        meta_uri:
          type: string
        meta_description:
          type: string
        meta_endescription:
          type: string
        meta_author:
          type: string
      example:
        id: 1
        meta_name: 名称
        meta_enname: name
        meta_version: 1.0.0
        meta_prefix: my
        meta_uri: http://myVocab/
        meta_description: テスト用の語彙です
        meta_endescription: The vocabulary for test
        meta_author: Yasutaka Moriwaki
    ReferenceVocabulary:
      type: object
      properties:
        id:
          type: integer
          format: int64
        term:
          type: string
        preferred_label:
          type: string
        language:
          type: string
        uri:
          type: string
        broader_term:
          type: string
        other_voc_syn_uri:
          type: string
        term_description:
          type: string
        created_time:
          type: string
        modified_time:
          type: string
        postion_x:
          type: string
        postion_y:
          type: string
      example:
        id: 1
        term: linux
        preferred_label: linux
        language: en
        uri: http://test/8/linux
        broader_term: http://myVocab/3
        other_voc_syn_uri: http://otherVocab/16
        term_description: 用語の説明です
        created_time: "2021-04-02T12:43:02Z"
        modified_time: "2021-04-08T16:07:59Z"
        postion_x: "100"
        postion_y: "100"
    GetAllSuccessResponse:
      type: object
      properties:
        EditingVocabulary:
          type: array
          items:
            $ref: '#/components/schemas/EditingVocabulary'
        EditingVocabularyMeta:
          type: array
          items:
            $ref: '#/components/schemas/EditingVocabularyMeta'
        ReferenceVocabulary:
          type: array
          items:
            $ref: '#/components/schemas/ReferenceVocabulary'
      example:
        EditingVocabulary:
        - id: 1
          term: os
          preferred_label: os
          language: ja
          uri: http://test/0/os
          broader_term: http://myVocab/3
          synonym: オペレーティングシステム
          other_voc_syn_uri: http://otherVocab/16
          term_description: 用語の説明です
          created_time: "2021-04-02T12:43:02Z"
          modified_time: "2021-04-08T16:07:59Z"
          synonym_candidate: 基本ソフト
          broader_term_candidate: プログラム
          postion_x: "100"
          postion_y: "100"
          color1: black
          color2: black
        EditingVocabularyMeta:
        - id: 1
          meta_name: 名称
          meta_enname: name
          meta_version: 1.0.0
          meta_prefix: my
          meta_uri: http://myVocab/
          meta_description: テスト用の語彙です
          meta_endescription: The vocabulary for test
          meta_author: Yasutaka Moriwaki
        ReferenceVocabulary:
        - id: 1
          term: linux
          preferred_label: linux
          language: en
          uri: http://test/8/linux
          broader_term: http://myVocab/3
          other_voc_syn_uri: http://otherVocab/16
          term_description: 用語の説明です
          created_time: "2021-04-02T12:43:02Z"
          modified_time: "2021-04-08T16:07:59Z"
          postion_x: "100"
          postion_y: "100"
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
      example:
        message: request is success.
    ErrorResponse:
      type: object
      properties:
        result:
          type: integer
        message:
          type: string
    CheckErrorResponse:
      type: object
      properties:
        phase:
          type: integer
        terms:
          type: array
          items:
            type: string
        langs:
          type: array
          items:
            type: string
        reason:
          type: integer
        file_type:
          type: integer
